language: python
python:
  - "3.6"
services:
  - postgresql
install:
  - pip3 install flask
  - pip3 install flask-sqlalchemy
  - pip3 install flask-psycopg2

before_script:
# - pip3 install -r requirements.txt
- psql -c 'create database thefarm;' -U postgres

script: pytest test/test.py
